// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"

import kinesis "github.com/aws/aws-sdk-go/service/kinesis"
import mock "github.com/stretchr/testify/mock"
import request "github.com/aws/aws-sdk-go/aws/request"

// KinesisPublisher is an autogenerated mock type for the KinesisPublisher type
type KinesisPublisher struct {
	mock.Mock
}

// PutRecordsWithContext provides a mock function with given fields: ctx, input, opts
func (_m *KinesisPublisher) PutRecordsWithContext(ctx context.Context, input *kinesis.PutRecordsInput, opts ...request.Option) (*kinesis.PutRecordsOutput, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, input)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *kinesis.PutRecordsOutput
	if rf, ok := ret.Get(0).(func(context.Context, *kinesis.PutRecordsInput, ...request.Option) *kinesis.PutRecordsOutput); ok {
		r0 = rf(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kinesis.PutRecordsOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *kinesis.PutRecordsInput, ...request.Option) error); ok {
		r1 = rf(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
