service: ${file(./setting.yml):service}

package:
  individually: true

provider:
  name: aws
  runtime: go1.x
  region: ${file(./setting.yml):region}
  stage: ${file(./setting.yml):stage}
  logRetentionInDays: 30
  tags:
    service: zamus
  iamRoleStatements:
    - Effect: 'Allow'
      Resource: '*'
      Action:
        - 'dynamodb:*'
        - 'lambda:*'

functions:
  service:
    handler: bin/app
    environment:
      APP_STAGE: ${self:provider.stage}
      APP_SERVICE: ${self:service}-${self:provider.stage}
      APP_VERSION: "1.0.0"
      APP_SENTRY_DSN: ${file(./setting.yml):sentry}
      APP_TABLE: ${self:service}-${self:provider.stage}
    memorySize: ${file(./setting.yml):memorySize}
    timeout: ${file(./setting.yml):timeout}
    package:
      include:
        - ./bin/app

resources:
  Resources:
    SAGAStore:
      Type: 'AWS::DynamoDB::Table'
      # DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: hk
            AttributeType: S
          - AttributeName: rk
            AttributeType: S
        KeySchema:
          - AttributeName: hk
            KeyType: HASH
          - AttributeName: rk
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:service}-${self:provider.stage}