// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import dql "github.com/onedaycat/zamus/dql"
import errors "github.com/onedaycat/errors"
import mock "github.com/stretchr/testify/mock"

// DQL is an autogenerated mock type for the DQL type
type DQL struct {
	mock.Mock
}

// AddError provides a mock function with given fields: appErr
func (_m *DQL) AddError(appErr errors.Error) {
	_m.Called(appErr)
}

// GetDQLErrors provides a mock function with given fields:
func (_m *DQL) GetDQLErrors() []*dql.DQLError {
	ret := _m.Called()

	var r0 []*dql.DQLError
	if rf, ok := ret.Get(0).(func() []*dql.DQLError); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dql.DQLError)
		}
	}

	return r0
}

// Retry provides a mock function with given fields:
func (_m *DQL) Retry() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Save provides a mock function with given fields: ctx, data
func (_m *DQL) Save(ctx context.Context, data []byte) errors.Error {
	ret := _m.Called(ctx, data)

	var r0 errors.Error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) errors.Error); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}

	return r0
}
