// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import dql "github.com/onedaycat/zamus/dql"
import mock "github.com/stretchr/testify/mock"

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// Save provides a mock function with given fields: ctx, dqlMsg
func (_m *Storage) Save(ctx context.Context, dqlMsg *dql.DQLMsg) error {
	ret := _m.Called(ctx, dqlMsg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dql.DQLMsg) error); ok {
		r0 = rf(ctx, dqlMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
