// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import zamus "github.com/onedaycat/zamus"
import mock "github.com/stretchr/testify/mock"

// EventBus is an autogenerated mock type for the EventBus type
type EventBus struct {
	mock.Mock
}

// Publish provides a mock function with given fields: events
func (_m *EventBus) Publish(events []*zamus.EventMessage) error {
	ret := _m.Called(events)

	var r0 error
	if rf, ok := ret.Get(0).(func([]*zamus.EventMessage) error); ok {
		r0 = rf(events)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
