// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import eventstore "github.com/onedaycat/zamus/eventstore"
import mock "github.com/stretchr/testify/mock"

// EventStore is an autogenerated mock type for the EventStore type
type EventStore struct {
	mock.Mock
}

// GetAggregate provides a mock function with given fields: ctx, aggID, agg
func (_m *EventStore) GetAggregate(ctx context.Context, aggID string, agg eventstore.AggregateRoot) error {
	ret := _m.Called(ctx, aggID, agg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, eventstore.AggregateRoot) error); ok {
		r0 = rf(ctx, aggID, agg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAggregateByTimeSeq provides a mock function with given fields: ctx, aggID, agg, timeSeq
func (_m *EventStore) GetAggregateByTimeSeq(ctx context.Context, aggID string, agg eventstore.AggregateRoot, timeSeq int64) error {
	ret := _m.Called(ctx, aggID, agg, timeSeq)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, eventstore.AggregateRoot, int64) error); ok {
		r0 = rf(ctx, aggID, agg, timeSeq)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetEvents provides a mock function with given fields: ctx, aggID, timeSeq
func (_m *EventStore) GetEvents(ctx context.Context, aggID string, timeSeq int64) ([]*eventstore.EventMsg, error) {
	ret := _m.Called(ctx, aggID, timeSeq)

	var r0 []*eventstore.EventMsg
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) []*eventstore.EventMsg); ok {
		r0 = rf(ctx, aggID, timeSeq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*eventstore.EventMsg)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, aggID, timeSeq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, agg
func (_m *EventStore) Save(ctx context.Context, agg eventstore.AggregateRoot) error {
	ret := _m.Called(ctx, agg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, eventstore.AggregateRoot) error); ok {
		r0 = rf(ctx, agg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveWithMetadata provides a mock function with given fields: ctx, agg, metadata
func (_m *EventStore) SaveWithMetadata(ctx context.Context, agg eventstore.AggregateRoot, metadata *eventstore.Metadata) error {
	ret := _m.Called(ctx, agg, metadata)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, eventstore.AggregateRoot, *eventstore.Metadata) error); ok {
		r0 = rf(ctx, agg, metadata)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetSnapshotEveryNEvents provides a mock function with given fields: n
func (_m *EventStore) SetSnapshotEveryNEvents(n int64) {
	_m.Called(n)
}
