// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import errors "github.com/onedaycat/errors"
import event "github.com/onedaycat/zamus/event"

import mock "github.com/stretchr/testify/mock"

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// Save provides a mock function with given fields: ctx, msgs
func (_m *Storage) Save(ctx context.Context, msgs []*event.Msg) errors.Error {
	ret := _m.Called(ctx, msgs)

	var r0 errors.Error
	if rf, ok := ret.Get(0).(func(context.Context, []*event.Msg) errors.Error); ok {
		r0 = rf(ctx, msgs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.Error)
		}
	}

	return r0
}
