service: ${file(./setting.yml):service}

package:
  individually: true

provider:
  name: aws
  runtime: go1.x
  region: ${file(./setting.yml):region}
  stage: ${file(./setting.yml):stage}
  iamRoleStatements:
    - Effect: 'Allow'
      Resource: '*'
      Action:
        - 'dynamodb:*'
        - 'kinesis:*'
        - 'lambda:*'

functions:
  dynamodb-kinesis:
    handler: dynamokinesis/bin/app
    environment:
      APP_STAGE: ${self:provider.stage}
      APP_SENTRY_DSN: ${file(./setting.yml):dynamokinesis.sentry}
      KINESIS_STREAM_NAMES: ${self:service}-stream-1-${self:provider.stage}
    memorySize: ${file(./setting.yml):dynamokinesis.memorySize}
    timeout: ${file(./setting.yml):dynamokinesis.timeout}
    events:
      - stream:
          type: dynamodb
          arn: { 'Fn::GetAtt': ['EventstoreEvent', 'StreamArn'] }
          batchSize: ${file(./setting.yml):dynamokinesis.batchSize}
          startingPosition: ${file(./setting.yml):dynamokinesis.startingPosition}
          enabled: true
      - schedule:
          name: warmer-${self:service}-${self:provider.stage}-dynamodb-kinesis
          rate: rate(10 minutes)
          enabled: true
          input:
            warmer: true
            concurrency: 1
    package:
      include:
        - ./dynamokinesis/bin/app
  firehose-transform:
    handler: firehosetransform/bin/app
    environment:
      APP_STAGE: ${self:provider.stage}
      APP_SENTRY_DSN: ${file(./setting.yml):firehosetransform.sentry}
    memorySize: ${file(./setting.yml):firehosetransform.memorySize}
    timeout: ${file(./setting.yml):firehosetransform.timeout}
    package:
      include:
        - ./firehosetransform/bin/app

resources:
  Resources:
    DynamodbDashKinesisLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: '30'
    FirehoseDashTransformLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: '30'
    EventstoreEvent:
      Type: 'AWS::DynamoDB::Table'
      # DeletionPolicy: Retain
      Properties:
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        AttributeDefinitions:
          - AttributeName: hk
            AttributeType: S
          - AttributeName: rk
            AttributeType: 'N'
        KeySchema:
          - AttributeName: hk
            KeyType: HASH
          - AttributeName: rk
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:service}-eventstore-${self:provider.stage}
    EventstoreSnapshot:
      Type: 'AWS::DynamoDB::Table'
      # DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: hk
            AttributeType: S
          - AttributeName: rk
            AttributeType: 'N'
        KeySchema:
          - AttributeName: hk
            KeyType: HASH
          - AttributeName: rk
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:service}-snapshot-${self:provider.stage}
    DQLstore:
      Type: 'AWS::DynamoDB::Table'
      # DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: hk
            AttributeType: S
          - AttributeName: rk
            AttributeType: S
        KeySchema:
          - AttributeName: hk
            KeyType: HASH
          - AttributeName: rk
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:service}-dql-${self:provider.stage}
    SagaStore:
      Type: 'AWS::DynamoDB::Table'
      # DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: hk
            AttributeType: S
          - AttributeName: rk
            AttributeType: S
        KeySchema:
          - AttributeName: hk
            KeyType: HASH
          - AttributeName: rk
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:service}-saga-${self:provider.stage}
    S3Event:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: ${self:service}-${self:provider.stage}
    FirehoseToS3Role:
      Type: AWS::IAM::Role
      # DeletionPolicy: Retain
      Properties:
        RoleName: ${self:service}-firehose-to-s3-${self:provider.stage}
        AssumeRolePolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - firehose.amazonaws.com
              Action: sts:AssumeRole
              Condition:
                StringEquals:
                  sts:ExternalId: ${file(./setting.yml):account}
        Policies:
          - PolicyName: KinesisToFirehoseToS3Policy
            PolicyDocument:
              Statement:
                - Effect: Allow
                  Action:
                    - kinesis:DescribeStream
                    - kinesis:GetShardIterator
                    - kinesis:GetRecords
                  Resource: '*'
                - Effect: Allow
                  Action:
                    - s3:AbortMultipartUpload
                    - s3:GetBucketLocation
                    - s3:GetObject
                    - s3:ListBucket
                    - s3:ListBucketMultipartUploads
                    - s3:PutObject
                  Resource:
                    - arn:aws:s3:::${self:service}-${self:provider.stage}
                    - arn:aws:s3:::${self:service}-${self:provider.stage}/*
                    - arn:aws:s3:::%FIREHOSE_BUCKET_NAME%
                    - arn:aws:s3:::%FIREHOSE_BUCKET_NAME%/*
                - Effect: Allow
                  Action:
                    - lambda:InvokeFunction
                    - lambda:GetFunctionConfiguration
                  Resource:
                    - arn:aws:lambda:${self:provider.region}:${file(./setting.yml):account}:function:${self:service}-${self:provider.stage}-firehose-transform:*
                - Effect: Allow
                  Action:
                    - logs:PutLogEvents
                  Resource: '*'
                - Effect: Allow
                  Action:
                    - glue:GetTableVersions
                  Resource: '*'
    KinesisOne:
      Type: AWS::Kinesis::Stream
      # DeletionPolicy: Retain
      Properties:
        Name: ${self:service}-stream-1-${self:provider.stage}
        RetentionPeriodHours: ${file(./setting.yml):kinesis-1.retentionPeriodHours}
        ShardCount: ${file(./setting.yml):kinesis-1.shardCount}
    Firehose:
      Type: AWS::KinesisFirehose::DeliveryStream
      DependsOn:
        - S3Event
        - FirehoseToS3Role
        - KinesisOne
        - GlueCreateTable
      # DeletionPolicy: Retain
      Properties:
        DeliveryStreamName: ${self:service}-firehose-${self:provider.stage}
        DeliveryStreamType: KinesisStreamAsSource
        KinesisStreamSourceConfiguration:
          KinesisStreamARN: arn:aws:kinesis:${self:provider.region}:${file(./setting.yml):account}:stream/${self:service}-stream-1-${self:provider.stage}
          RoleARN: { Fn::GetAtt: [FirehoseToS3Role, Arn] }
        ExtendedS3DestinationConfiguration:
          BucketARN:
            Fn::Join:
              - ''
              - - 'arn:aws:s3:::'
                - Ref: S3Event
          RoleARN: { Fn::GetAtt: [FirehoseToS3Role, Arn] }
          # firehose/dt=!{timestamp:yyyy-MM-dd}/
          Prefix: 'firehose/'
          # ErrorOutputPrefix: "errors/!{firehose:error-output-type}/dt=!{timestamp:yyyy-MM-dd}/"
          CompressionFormat: UNCOMPRESSED
          BufferingHints:
            IntervalInSeconds: ${file(./setting.yml):firehose.intervalInSeconds}
            SizeInMBs: ${file(./setting.yml):firehose.sizeInMBs}
          # CloudWatchLoggingOptions:
          # Enabled: true
          # LogGroupName: String
          # LogStreamName: String
          ProcessingConfiguration:
            Enabled: true
            Processors:
              - Parameters:
                  - ParameterName: LambdaArn
                    ParameterValue: arn:aws:lambda:${self:provider.region}:${file(./setting.yml):account}:function:${self:service}-${self:provider.stage}-firehose-transform
                Type: Lambda
          # DataFormatConversionConfiguration:
          #   Enabled: true
          #   SchemaConfiguration:
          #     CatalogId: ${file(./setting.yml):account}
          #     DatabaseName: ${self:service}_${self:provider.stage}
          #     TableName: eventstore
          #     OutputFormatConfiguration:
          #       ParquetSerDe:
          #         Compression: SNAPPY
          #     RoleARN: { Fn::GetAtt: [FirehoseToS3Role, Arn] }
    GlueCreateDatabase:
      Type: AWS::Glue::Database
      # DeletionPolicy: Retain
      Properties:
        DatabaseInput:
          Name: ${file(./setting.yml):glue.database}_${self:provider.stage}
        CatalogId: ${file(./setting.yml):account}
    GlueCreateTable:
      Type: AWS::Glue::Table
      # DeletionPolicy: Retain
      DependsOn:
        - S3Event
        - GlueCreateDatabase
      Properties:
        DatabaseName: ${file(./setting.yml):glue.database}_${self:provider.stage}
        CatalogId: ${file(./setting.yml):account}
        TableInput:
          Name: eventstore
          TableType: EXTERNAL_TABLE
          PartitionKeys:
            - { Name: dt, Type: string }
          StorageDescriptor:
            Compressed: false
            Location: 's3://${self:service}-${self:provider.stage}/firehose/'
            InputFormat: 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
            OutputFormat: 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
            Columns:
              - { Name: id, Type: string }
              - { Name: aggID, Type: string }
              - { Name: eventType, Type: string }
              - { Name: event, Type: string }
              - { Name: time, Type: bigint }
              - { Name: seq, Type: bigint }
              - { Name: metadata, Type: 'map<string,string>' }
            SerdeInfo:
              SerializationLibrary: 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
              Parameters:
                serialization.format: '1'
