service: ${file(./setting.yml):service}

package:
  individually: true

provider:
  name: aws
  runtime: go1.x
  region: ${file(./setting.yml):region}
  stage: ${file(./setting.yml):stage}
  iamRoleStatements:
    - Effect: 'Allow'
      Resource: '*'
      Action:
        - 'dynamodb:*'
        - 'kinesis:*'
        - 'lambda:*'

functions:
  dynamodb-kinesis:
    handler: dynamokinesis/bin/app
    environment:
      APP_STAGE: ${self:provider.stage}
      APP_SENTRY_DSN: ${file(./setting.yml):dynamokinesis.sentry}
      KINESIS_STREAM_NAMES: ${self:service}-stream-1-${self:provider.stage}
    memorySize: ${file(./setting.yml):dynamokinesis.memorySize}
    timeout: ${file(./setting.yml):dynamokinesis.timeout}
    events:
      - stream:
          type: dynamodb
          arn: { 'Fn::GetAtt': ['EventstoreEvent', 'StreamArn'] }
          batchSize: ${file(./setting.yml):dynamokinesis.batchSize}
          startingPosition: ${file(./setting.yml):dynamokinesis.startingPosition}
          enabled: true
    package:
      include:
        - ./dynamokinesis/bin/app

resources:
  Resources:
    DynamodbDashKinesisLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: '30'
    EventstoreEvent:
      Type: 'AWS::DynamoDB::Table'
      # DeletionPolicy: Retain
      Properties:
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        AttributeDefinitions:
          - AttributeName: hk
            AttributeType: S
          - AttributeName: rk
            AttributeType: 'N'
        KeySchema:
          - AttributeName: hk
            KeyType: HASH
          - AttributeName: rk
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:service}-eventstore-${self:provider.stage}
    EventstoreSnapshot:
      Type: 'AWS::DynamoDB::Table'
      # DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: hk
            AttributeType: S
          - AttributeName: rk
            AttributeType: 'N'
        KeySchema:
          - AttributeName: hk
            KeyType: HASH
          - AttributeName: rk
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:service}-snapshot-${self:provider.stage}
    DQLstore:
      Type: 'AWS::DynamoDB::Table'
      # DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: hk
            AttributeType: S
          - AttributeName: rk
            AttributeType: S
        KeySchema:
          - AttributeName: hk
            KeyType: HASH
          - AttributeName: rk
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:service}-dql-${self:provider.stage}
    SagaStore:
      Type: 'AWS::DynamoDB::Table'
      # DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: hk
            AttributeType: S
          - AttributeName: rk
            AttributeType: S
        KeySchema:
          - AttributeName: hk
            KeyType: HASH
          - AttributeName: rk
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:service}-saga-${self:provider.stage}
