name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: onedaycat/ci
    steps:
      - uses: actions/checkout@v1
      - run: env
      - run: mage test
